### ISSUE TITLE
Didn't shutdown after print was complete

### ISSUE THREAD

**Issue by mattadata** [jamesmccannon02/OctoPrint-Tplinkautoshutdown#14]
I installed the plugin and it works when you use the buttons at the top of OctoPrint screen to swith the Kasa plug off/on.
But after completing a print, it didn't turn the Kasa plug off. Any ideas?

**Comment by mattadata** [comment]
Nevermind. The IP address changed. I will make it static.

**Comment by jamesmccannon02** [comment]
No problem, I was worried for a second.
