### ISSUE TITLE
Style change to the nav-bar 

### ISSUE THREAD

**Issue by jamesmccannon02** [jamesmccannon02/OctoPrint-Tplinkautoshutdown#17]
![](https://user-images.githubusercontent.com/17956005/108634234-adf55000-7446-11eb-8037-0f91d17cdd5e.png)

Add padding to the right hand edge of the on button.

**Comment by Guddu327** [comment]
Hello, I think I have got understood the issue and would like to contribute to this.

**Comment by jamesmccannon02** [comment]
Sure take a fork of the repo and then submit a pull request once it is done and i'll add it to the master branch when done.

**Comment by Guddu327** [comment]
I have created a pull request for the issue. Please lemme know if that helps.
