### ISSUE TITLE
Getting Errors When Downloading 

### ISSUE THREAD

**Issue by nichols89ben** [jamesmccannon02/OctoPrint-Tplinkautoshutdown#18]
ERROR: Could not find a version that satisfies the requirement python-kasa (from OctoPrint-Tplinkautoshutdown==0.2.1) (from versions: none)ERROR: No matching distribution found for python-kasa (from OctoPrint-Tplinkautoshutdown==0.2.1)Error!Could not parse output from pip, see plugin_pluginmanager_console.log for generated output

I apologize in advance If I'm doing something wrong

**Comment by jamesmccannon02** [comment]
Can i ask what device you are running this on. What your operating system version is for OctoPrint and if you know what version of python you are running on

**Comment by nichols89ben** [comment]
Hi, thanks for your reply. Raspberry Pi 3 B+, Octoprint Version 1.5.3, and
not sure of the last one, just tried to upload with the URL .

Thanks,

*Ben Nichols*

**Comment by nichols89ben** [comment]
Found Python 2.7.16

**Comment by jamesmccannon02** [comment]
Ok, so you need to update your OctoPrint to use python3. There are two options. Either by updating using [https://octoprint.org/blog/2020/09/10/upgrade-to-py3/](https://octoprint.org/blog/2020/09/10/upgrade-to-py3/). However this method is hit and miss. For me it didn't work. Or install OctoPi 0.18 [https://octoprint.org/download/](https://octoprint.org/download/). The python2 version will be discontinued soon i didn't develop it to work with python2.

**Comment by nichols89ben** [comment]
It was me! That worked, thank you!
