### ISSUE TITLE
Didn't Auto Shut Down

### ISSUE THREAD

**Issue by Padraig1980** [jamesmccannon02/OctoPrint-Tplinkautoshutdown#22]
I can turn the plug on and off with the embedded buttons but it does not turn off automatically after print finishes. 
I'm using HS103 and have made the IP static.
Any ideas?

**Comment by jamesmccannon02** [comment]
Which version of the auto-shutdown plugin are you using?

**Comment by jamesmccannon02** [comment]
Can you also check if you are using version 0.2.1 that if you are not using a timelapse, you need to turn off the wait for timelapse to render otherwise it will not turn off.

**Comment by Padraig1980** [comment]
0.2.1
Timelapse was the issue. Never thought to uncheck that. 
Thank you for your help.
