### ISSUE TITLE
not able to install via plug in manager

### ISSUE THREAD

**Issue by turbodlr** [jamesmccannon02/OctoPrint-Tplinkautoshutdown#25]
first I dont see it in search so I used the url copied from  here.  I get these errors, can you advise?  

ERROR: Could not find a version that satisfies the requirement python-kasa (from OctoPrint-Tplinkautoshutdown==0.2.1) (from versions: none)
ERROR: No matching distribution found for python-kasa (from OctoPrint-Tplinkautoshutdown==0.2.1)
Error!
Could not parse output from pip, see plugin_pluginmanager_console.log for generated output

**Comment by turbodlr** [comment]
here is the entire output of the attempted install

Installing plugin from https://github.com/jamesmccannon02/OctoPrint-Tplinkautoshutdown/archive/master.zip...
/home/pi/oprint/bin/python2 -m pip --disable-pip-version-check install file:///tmp/tmpNb8337/master.zip --no-cache-dir
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Processing /tmp/tmpNb8337/master.zip
Requirement already satisfied: OctoPrint in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint-Tplinkautoshutdown==0.2.1) (1.5.3)
ERROR: Could not find a version that satisfies the requirement python-kasa (from OctoPrint-Tplinkautoshutdown==0.2.1) (from versions: none)
ERROR: No matching distribution found for python-kasa (from OctoPrint-Tplinkautoshutdown==0.2.1)
Error!
Could not parse output from pip, see plugin_pluginmanager_console.log for generated output

**Comment by jamesmccannon02** [comment]
Ok so I believe your problem is your using python 2 which is now about to be discontinued as we move to python 3. What device are you using?

**Comment by turbodlr** [comment]
Pi 4b

**Comment by turbodlr** [comment]
Linux octopi 4.19.75-v7l+  
OctoPrint version : 1.5.3
OctoPi version    : 0.17.0

**Comment by jamesmccannon02** [comment]
Ok, so your issue is that you are running python 2. So you need to either re-install octopi as the new version is now python 3 or follow the tutorial to convert your current version to python 3

[https://octoprint.org/blog/2020/09/10/upgrade-to-py3/](https://octoprint.org/blog/2020/09/10/upgrade-to-py3/)

**Comment by jamesmccannon02** [comment]
https://octoprint.org/download/

**Comment by turbodlr** [comment]
cool, standby will try and advise, thanks!

**Comment by jamesmccannon02** [comment]
Using the update tool is unreliable. It either works or it doesn't but this needs to be done in the next month if you still want to use octoprint as the owner of octoprint is fully removing all support next month

**Comment by turbodlr** [comment]
ok  upgrade successful and plugin install worked now.  Thanks for the fast reply!

**Comment by jamesmccannon02** [comment]
No problem enjoy
