### ISSUE TITLE
Improve confirmation modal

### ISSUE THREAD

**Issue by ibexes** [jamesmccannon02/OctoPrint-Tplinkautoshutdown#34]
Alerts are ugly and annoying, if a UI refactor is ever done, consider using a more interactive modal for confirmations when powering off/powering on.

**Comment by jamesmccannon02** [comment]
I can look into this in the future. If you wanted to contribute, more than happy if you wanted to give it a go and show me what you prefer.

**Comment by jamesmccannon02** [comment]
I have reduce the number of alerts and will look more in the future to further reduce the use them. However I want to find a way that still ensures and double checks that this is the action that is definitely wanted. As a result, the use of the alert is the most simple way to do this with the current knowledge that I have
