### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by meltonpieman** [jamesmccannon02/OctoPrint-Tplinkautoshutdown#35]
Your plugin does not appear in my Plugin Manager list and a manual install fails as well.

**Comment by jamesmccannon02** [comment]
Ok, so your issue is that you are running python 2. So you need to either re-install octopi as the new version is now python 3 or follow the tutorial to convert your current version to python 3

https://octoprint.org/blog/2020/09/10/upgrade-to-py3/

**Comment by jamesmccannon02** [comment]
https://octoprint.org/download/

**Comment by meltonpieman** [comment]
Thanks for that. I will do it.

**Comment by jamesmccannon02** [comment]
@meltonpieman Did this solve you problem?
