### ISSUE TITLE
Says this package needs a different Python..

### ISSUE THREAD

**Issue by Bromley47** [jamesmccannon02/OctoPrint-Tplinkautoshutdown#38]
Tried to install using URL pasted into Plug In manager but get this message:-

ERROR: Package 'OctoPrint-Tplinkautoshutdown' requires a different Python: 2.7.16 not in '>=3,<4'
Error!
Could not parse output from pip, see plugin_pluginmanager_console.log for generated output

As far as I can tell have Python 3.7.3 installed but not sure if this is default. How does a nooby check this and install the package?

Any help appreciated. Want to try this instead of TP-Link SmartPlug plug in as I don't think that is compatible with the KSA HS100 Smart Plug. That doesn't seem to switch off the printer when idle or after a print has completed.

**Comment by jamesmccannon02** [comment]
Ok, so your issue is that you are running python 2. So you need to either re-install octopi as the new version is now python 3 or follow the tutorial to convert your current version to python 3

https://octoprint.org/blog/2020/09/10/upgrade-to-py3/

**Comment by jamesmccannon02** [comment]
https://octoprint.org/download/

**Comment by jamesmccannon02** [comment]
I personally use the HS100 and it works.

**Comment by Bromley47** [comment]
Thank you James I will do that next

**Comment by Bromley47** [comment]
That worked James after Puthon3 installed  but someone compared this to TP-Link Sm plug in which had all the singing and dancing configurations such as thermal runaway monitoring, power off on idle, etc etc. Am I missing something here or are these just not included in this plug in?

**Comment by jamesmccannon02** [comment]
Hi, no this plugin currently doesn't have all these features but will most likely in time. The main approach though with this plugin is to make the process simpler for those that don't need all the extra features and instead want a simple tick box design

**Comment by Bromley47** [comment]
Ok James I understand- the TP-Link plug in was complicated! And then never shut off after a print finished - hope this one does!

Regards
Glenn

**Comment by jamesmccannon02** [comment]
If you ever have an issue with my plugin please raise an issue. I try to reply quickly and if code breaks i also try to fix it quickly
