### ISSUE TITLE
Does not work with hs110

### ISSUE THREAD

**Issue by Ukchris79** [jamesmccannon02/OctoPrint-Tplinkautoshutdown#43]
I can not get it to work with my HS110, could it be that it is because you do not have any user login details?

Model HS110
Firmware 1.1.0
Hardware Ver 4.1

**Comment by jamesmccannon02** [comment]
Can i ask what country you are in and to provide screenshots of your settings

**Comment by Ukchris79** [comment]
I am in the UK, it looks like they have done something to the firmware that kills UK versions, your program is not the only one effected

[https://github.com/jneilliii/OctoPrint-TPLinkSmartplug/issues/218](url)

**Comment by jamesmccannon02** [comment]
Hi, I am curious as I am in the UK and use the same plug and am not having the issue. Would be interested to resolve this for you if you can provide as much info as possible. Logs and screenshots of your settings. The link you provided used a different style of connecting to the device so doesn't necessarily mean that this plugin wont work.

**Comment by jamesmccannon02** [comment]
From previous users, some have had checked the wait until timelapse render option. If you don't use a timelapse, this will break the plugin so must be turned off for the plugin to work if you don't use the timelapse feature

**Comment by Ukchris79** [comment]
I am currently printing thus I can't enable the plugin, I will check again tomorrow to get the settings

**Comment by Ukchris79** [comment]
![hs110](https://user-images.githubusercontent.com/66808457/110608539-43514d80-8184-11eb-8f19-9961c186da01.PNG)

I have also factory reset the plug

**Comment by jamesmccannon02** [comment]
Did you remember to restart the server

**Comment by jamesmccannon02** [comment]
could you go into settings > logs and download the console.log file. This may be able to help me solve the issue.

**Comment by Ukchris79** [comment]
[plugin_pluginmanager_console.log](https://github.com/jamesmccannon02/OctoPrint-Tplinkautoshutdown/files/6116741/plugin_pluginmanager_console.log)

**Comment by jamesmccannon02** [comment]
Thanks, this shows that it has been successfully installed into OctoPrint. As well as this, can you also send the standard ``OctoPrint.log`` file. This will show me a log of all events taking place such as print done events which is used to control the plug. Additionally this log file also shows runtime errors rather than errors on plugin installation.

**Comment by jamesmccannon02** [comment]
Hi, sorry about the late reply but didn't recieve it. Did you send it to james@mccannon.co.uk

**Comment by Ukchris79** [comment]
Email sent

**Comment by jamesmccannon02** [comment]
I believe I may be dealing with a similar issue could you try the following to see if the issue is similar

**Comment by jamesmccannon02** [comment]
Looking at the current log it looks as if the configs haven't been saved into the config file. Have a look at the config.yaml file within .octoprint. In there you should see plugins: then under that TpLinkAutoShutdown. This will list all the settings you have set/changed from the defaults

**Comment by jamesmccannon02** [comment]
Could you take a look at that and add a few screenshots. Thanks

**Comment by Ukchris79** [comment]
So I may be doing something wrong, but  I don't have a config.yaml in that folder
![Capture](https://user-images.githubusercontent.com/66808457/111000529-1d8d9980-837a-11eb-83ac-1e7e812e165f.PNG)

**Comment by jamesmccannon02** [comment]
so currently you are in the ``OctoPrint`` file but if you go to ``~/.octoprint`` it will be in there. Run the command ``cd ~/.octoprint`` to get in the file then ``ls`` and it should show up.

If you go back to your home directory ``~/`` and ran ``ls -a`` it would have shown up but it is a hidden file and as a result, you needed ``-a`` to be able to see it at the end of the ``ls`` statement.

**Comment by Ukchris79** [comment]
So I had a look in the config.yaml and there is no mention of your plug-in (I can not post a screen shot as there are plugins with PWs etc surrounding where it should be)

I uninstalled it and tried to reinstall the plug in, here is the output from the installation script.

Installing plugin "OctoPrint-TpLinkAutoShutdown" from https://github.com/jamesmccannon02/OctoPrint-Tplinkautoshutdown/archive/master.zip...
/home/pi/oprint/bin/python3 -m pip --disable-pip-version-check install file:///tmp/tmpin93u1ya/OctoPrint-Tplinkautoshutdown-master.zip --no-cache-dir
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Processing /tmp/tmpin93u1ya/OctoPrint-Tplinkautoshutdown-master.zip
Requirement already satisfied: OctoPrint in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint-Tplinkautoshutdown==1.0.2) (1.5.3)
Requirement already satisfied: python-kasa in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint-Tplinkautoshutdown==1.0.2) (0.4.0.dev2)
Requirement already satisfied: Jinja2<3,>=2.11.2 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Tplinkautoshutdown==1.0.2) (2.11.2)
Requirement already satisfied: sentry-sdk<1,>=0.15.1 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Tplinkautoshutdown==1.0.2) (0.19.5)
Requirement already satisfied: semantic-version<3,>=2.8.5 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Tplinkautoshutdown==1.0.2) (2.8.5)
Requirement already satisfied: frozendict<2,>=1.2 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Tplinkautoshutdown==1.0.2) (1.2)
Requirement already satisfied: tornado==5.1.1 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Tplinkautoshutdown==1.0.2) (5.1.1)
Requirement already satisfied: requests<3,>=2.23.0 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Tplinkautoshutdown==1.0.2) (2.25.1)
Requirement already satisfied: blinker<2,>=1.4 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Tplinkautoshutdown==1.0.2) (1.4)
Requirement already satisfied: rsa==4.0 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Tplinkautoshutdown==1.0.2) (4.0)
Requirement already satisfied: markdown<3.2,>=3.1 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Tplinkautoshutdown==1.0.2) (3.1.1)
Requirement already satisfied: pylru<2,>=1.2 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Tplinkautoshutdown==1.0.2) (1.2.0)
Requirement already satisfied: Flask-Babel<2,>=1.0 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Tplinkautoshutdown==1.0.2) (1.0.0)
Requirement already satisfied: regex!=2018.11.6 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Tplinkautoshutdown==1.0.2) (2020.11.13)
Requirement already satisfied: unidecode<0.05,>=0.04.14 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Tplinkautoshutdown==1.0.2) (0.4.21)
Requirement already satisfied: pyserial<4,>=3.4 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Tplinkautoshutdown==1.0.2) (3.5)
Requirement already satisfied: markupsafe<2.0,>=1.1 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Tplinkautoshutdown==1.0.2) (1.1.1)
Requirement already satisfied: flask<2,>=1.1.2 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Tplinkautoshutdown==1.0.2) (1.1.2)
Requirement already satisfied: netaddr<1,>=0.7.19 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Tplinkautoshutdown==1.0.2) (0.8.0)
Requirement already satisfied: sarge==0.1.5post0 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Tplinkautoshutdown==1.0.2) (0.1.5.post0)
Requirement already satisfied: pkginfo<2,>=1.5.0.1 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Tplinkautoshutdown==1.0.2) (1.6.1)
Requirement already satisfied: Click<8,>=7.1.2 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Tplinkautoshutdown==1.0.2) (7.1.2)
Requirement already satisfied: wrapt<2,>=1.12.1 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Tplinkautoshutdown==1.0.2) (1.12.1)
Requirement already satisfied: emoji<1,>=0.5.4 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Tplinkautoshutdown==1.0.2) (0.6.0)
Requirement already satisfied: itsdangerous<2,>=1.1.0 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Tplinkautoshutdown==1.0.2) (1.1.0)
Requirement already satisfied: filetype<2,>=1.0.7 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Tplinkautoshutdown==1.0.2) (1.0.7)
Requirement already satisfied: Flask-Login<0.6,>=0.5 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Tplinkautoshutdown==1.0.2) (0.5.0)
Requirement already satisfied: cachelib<1,>=0.1 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Tplinkautoshutdown==1.0.2) (0.1.1)
Requirement already satisfied: netifaces<1,>=0.10.9 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Tplinkautoshutdown==1.0.2) (0.10.9)
Requirement already satisfied: OctoPrint-FirmwareCheck>=2020.09.23 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Tplinkautoshutdown==1.0.2) (2021.2.4)
Requirement already satisfied: websocket-client<1,>=0.57 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Tplinkautoshutdown==1.0.2) (0.57.0)
Requirement already satisfied: feedparser<7,>=6.0.2 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Tplinkautoshutdown==1.0.2) (6.0.2)
Requirement already satisfied: future<1,>=0.18.2 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Tplinkautoshutdown==1.0.2) (0.18.2)
Requirement already satisfied: psutil<6,>=5.7 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Tplinkautoshutdown==1.0.2) (5.8.0)
Requirement already satisfied: zeroconf<0.25,>=0.24 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Tplinkautoshutdown==1.0.2) (0.24.5)
Requirement already satisfied: werkzeug<2,>=1.0.1 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Tplinkautoshutdown==1.0.2) (1.0.1)
Requirement already satisfied: OctoPrint-FileCheck>=2020.08.07 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Tplinkautoshutdown==1.0.2) (2021.2.23)
Requirement already satisfied: PyYAML<6,>=5.3.1 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Tplinkautoshutdown==1.0.2) (5.3.1)
Requirement already satisfied: Flask-Assets<3,>=2.0 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Tplinkautoshutdown==1.0.2) (2.0)
Requirement already satisfied: watchdog==0.10.4 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Tplinkautoshutdown==1.0.2) (0.10.4)
Requirement already satisfied: pyasn1>=0.1.3 in /home/pi/oprint/lib/python3.7/site-packages (from rsa==4.0->OctoPrint->OctoPrint-Tplinkautoshutdown==1.0.2) (0.4.8)
Requirement already satisfied: pathtools>=0.1.1 in /home/pi/oprint/lib/python3.7/site-packages (from watchdog==0.10.4->OctoPrint->OctoPrint-Tplinkautoshutdown==1.0.2) (0.1.2)
Requirement already satisfied: sgmllib3k in /home/pi/oprint/lib/python3.7/site-packages (from feedparser<7,>=6.0.2->OctoPrint->OctoPrint-Tplinkautoshutdown==1.0.2) (1.0.0)
Requirement already satisfied: webassets>=2.0 in /home/pi/oprint/lib/python3.7/site-packages (from Flask-Assets<3,>=2.0->OctoPrint->OctoPrint-Tplinkautoshutdown==1.0.2) (2.0)
Requirement already satisfied: Babel>=2.3 in /home/pi/oprint/lib/python3.7/site-packages (from Flask-Babel<2,>=1.0->OctoPrint->OctoPrint-Tplinkautoshutdown==1.0.2) (2.9.0)
Requirement already satisfied: pytz in /home/pi/oprint/lib/python3.7/site-packages (from Flask-Babel<2,>=1.0->OctoPrint->OctoPrint-Tplinkautoshutdown==1.0.2) (2020.5)
Requirement already satisfied: setuptools>=36 in /home/pi/oprint/lib/python3.7/site-packages (from markdown<3.2,>=3.1->OctoPrint->OctoPrint-Tplinkautoshutdown==1.0.2) (51.1.2)
Requirement already satisfied: certifi>=2017.4.17 in /home/pi/oprint/lib/python3.7/site-packages (from requests<3,>=2.23.0->OctoPrint->OctoPrint-Tplinkautoshutdown==1.0.2) (2020.12.5)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/pi/oprint/lib/python3.7/site-packages (from requests<3,>=2.23.0->OctoPrint->OctoPrint-Tplinkautoshutdown==1.0.2) (1.26.2)
Requirement already satisfied: chardet<5,>=3.0.2 in /home/pi/oprint/lib/python3.7/site-packages (from requests<3,>=2.23.0->OctoPrint->OctoPrint-Tplinkautoshutdown==1.0.2) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in /home/pi/oprint/lib/python3.7/site-packages (from requests<3,>=2.23.0->OctoPrint->OctoPrint-Tplinkautoshutdown==1.0.2) (2.10)
Requirement already satisfied: six in /home/pi/oprint/lib/python3.7/site-packages (from websocket-client<1,>=0.57->OctoPrint->OctoPrint-Tplinkautoshutdown==1.0.2) (1.15.0)
Requirement already satisfied: ifaddr in /home/pi/oprint/lib/python3.7/site-packages (from zeroconf<0.25,>=0.24->OctoPrint->OctoPrint-Tplinkautoshutdown==1.0.2) (0.1.7)
Requirement already satisfied: asyncclick<8,>=7 in /home/pi/oprint/lib/python3.7/site-packages (from python-kasa->OctoPrint-Tplinkautoshutdown==1.0.2) (7.1.2.3)
Requirement already satisfied: importlib-metadata in /home/pi/oprint/lib/python3.7/site-packages (from python-kasa->OctoPrint-Tplinkautoshutdown==1.0.2) (3.7.2)
Requirement already satisfied: anyio>=2 in /home/pi/oprint/lib/python3.7/site-packages (from asyncclick<8,>=7->python-kasa->OctoPrint-Tplinkautoshutdown==1.0.2) (2.2.0)
Requirement already satisfied: sniffio>=1.1 in /home/pi/oprint/lib/python3.7/site-packages (from anyio>=2->asyncclick<8,>=7->python-kasa->OctoPrint-Tplinkautoshutdown==1.0.2) (1.2.0)
Requirement already satisfied: typing-extensions in /home/pi/oprint/lib/python3.7/site-packages (from anyio>=2->asyncclick<8,>=7->python-kasa->OctoPrint-Tplinkautoshutdown==1.0.2) (3.7.4.3)
Requirement already satisfied: zipp>=0.5 in /home/pi/oprint/lib/python3.7/site-packages (from importlib-metadata->python-kasa->OctoPrint-Tplinkautoshutdown==1.0.2) (3.4.1)
Building wheels for collected packages: OctoPrint-Tplinkautoshutdown
Building wheel for OctoPrint-Tplinkautoshutdown (setup.py): started
Building wheel for OctoPrint-Tplinkautoshutdown (setup.py): finished with status 'done'
Created wheel for OctoPrint-Tplinkautoshutdown: filename=OctoPrint_Tplinkautoshutdown-1.0.2-py2.py3-none-any.whl size=9321 sha256=e43352fe6e4d7adc1cf67b3600a29b0a174de10d5dc554feec04b2fa7b62dcac
Stored in directory: /tmp/pip-ephem-wheel-cache-cxuyo0wf/wheels/8f/9d/29/3de55c7cadad6921f1b6944a0e5a33d39dd021d40692cf8851
Successfully built OctoPrint-Tplinkautoshutdown
Installing collected packages: OctoPrint-Tplinkautoshutdown
Successfully installed OctoPrint-Tplinkautoshutdown-1.0.2
Done!

**Comment by jamesmccannon02** [comment]
Hi, This shows that it has installed correctly. Therefore, I believe something else is causing the issue. If it is because OctoPrint isn't storing the settings this may in time become an issue with other plugins. I would try if you have a spare SD card installing OctoPrint again and then putting the plugin into the new OctoPrint server. If this works you know that it is an issue with OctoPrint and all you will need to do it a fresh install. Else, this is most likely a networking issue. @Ukchris79

**Comment by Ukchris79** [comment]
James

I think we have gone as far as we can with this, thanks for trying to sort it out.

I have made a fresh install of octoprint and only installed your plugin, unfortunately I get the same result. I do not expect that this is a network issue as they are on the same lan and there are no firewalls in place.

I suspect it is as I originally posted and TPlink have done something to the firmware, hopefully they will revert it in the future.

just in case it help you or anyone else, my model was a HS110(UK) Ver 4.1
