### ISSUE TITLE
Request for timer function at the time of automatic shutdown

### ISSUE THREAD

**Issue by san20210311** [jamesmccannon02/OctoPrint-Tplinkautoshutdown#45]
Dear developer

I am very grateful for using OctoPrint-TpLinkAutoShutdown.

At the time of automatic shutdown, the timer function (for example, after 5 minutes, 10 minutes, etc.) is used to turn off the power after m hours have passed.
In that case, there is a request that damage to 3D printers, etc. could be prevented due to power failure.

**Comment by jamesmccannon02** [comment]
This has already been opened as a request elsewhere.
