### ISSUE TITLE
 Auto-shutdown doesn't work if  Wait for Timelapes to Render is enabled

### ISSUE THREAD

**Issue by laprjns** [jamesmccannon02/OctoPrint-Tplinkautoshutdown#50]
Tile says it all.  Reverting back to 1.03 resolves the problem.    Printer is an Ender 3.  Octoprint is installed on a Laptop running Slackware Linux. 
Edit:  Forgot to mention that this is with a Smart Switch selected.

**Comment by jamesmccannon02** [comment]
Hi, i don't understand your question. Could you elaborate further what the problem is. Did you have timelapse setup with a webcam. Otherwise the event when the rendering process will never be triggered as it doesn't happen.

**Comment by laprjns** [comment]
Yes, I have timelapse setup and working.  TplinkAutoshutdown Version 1.0.3, with both Auto-shutdown and Wait for Timelapes to Render enabled, the printer would shut down after the timelapse rendering was completed.  After upgrading to version 1.0.4, and with both Auto-shutdown and Wait for Timelapse to Render are enabled,  the printer no longer shuts down. If i disable Wait for Timelapse to Render, then the printer does shut down properly at the end of the print.  Note that in all cases the time lapse did complete its rendering.
Hope this helps.

**Comment by fenixryan** [comment]
Ditto same issue since upgrade to 1.0.4 can use the web buttons to switch strip device on and of but auto power off broken

**Comment by jamesmccannon02** [comment]
Hi thanks for letting me know. Currently looking into this issue.

**Comment by jamesmccannon02** [comment]
@laprjns @fenixryan Sorry or the delay but version ``1.1.0`` should have fixed this issue now. Let me know how you get on. Also please read the release notes as you need to re-set the device type due to other changes made in version ``1.1.0``
