### ISSUE TITLE
1.1.1

### ISSUE THREAD

**Issue by fenixryan** [jamesmccannon02/OctoPrint-Tplinkautoshutdown#54]
HI James
1.1.1 stuck in update loop. Tried two octo's servers. Did a complete uninstall, then re-install. Grabbed 1.1.0 then says update available. but doesn't update.

**Comment by jamesmccannon02** [comment]
Ok sorry. This will be my fault as I didn't change the update number when publishing the update. I'll get this fixed.

**Comment by jamesmccannon02** [comment]
This issue should now be fixed. Although it will require installing version 1.1.2
