### ISSUE TITLE
Did you forget to change the version number?

### ISSUE THREAD

**Issue by th3obituary** [jamesmccannon02/OctoPrint-Tplinkautoshutdown#56]
just installed 1.1.3 for the 3rd time. First time i thought i read it wrong or paid no attention and there were 2 updates but after installing 1.1.3 again it still shows as 1.1.2 and says update available. Tried uninstalling completely then reinstalling just to make sure and still the same.

**Comment by Tw0bit** [comment]
Same for me. It appears the version number is 1.1.2 in setup.py in the repo and release file.

**Comment by jamesmccannon02** [comment]
Hi, yes you are correct. Just published version 1.1.4 to solve this issue.
