### ISSUE TITLE
KP303 FW 1.0.10 not working

### ISSUE THREAD

**Issue by aaronsta1** [jamesmccannon02/OctoPrint-Tplinkautoshutdown#59]
i entered the IP, i set everything up. restarted the server but nothing.
one thing i see is the name and firmware reads "undefined" 

im pretty sure i have the right IP, its being shown in my router as connected device.

any ideas?

**Comment by jamesmccannon02** [comment]
What device are you using in terms of the plug?

Also can you attach as screenshot of your settings as that will help a lot.

**Comment by aaronsta1** [comment]
what do you mean? you mean my router? its a xr500.
https://flic.kr/p/2kW5ppP
https://flic.kr/p/2kW5ppt

**Comment by jamesmccannon02** [comment]
Hi, so these settings look to be correct. Only thing i would suggest is that you should restart you device now and try using the manual buttons at the top of the page. Also, the other thing that you should try is putting the octopi onto the 192.168.1 ip address as this may be causing a conflict if it is on 192.168.0 address. Let me know how you get on
