### ISSUE TITLE
It is possible for this plug-in work with P100?

### ISSUE THREAD

**Issue by NpFaith** [jamesmccannon02/OctoPrint-Tplinkautoshutdown#62]
Hi, thanks for the work you have done so far. It is possible for this plug-in work with P100? Its so cheap now...

https://www.tp-link.com/en/home-networking/smart-plug/tapo-p100/

Thanks for your time

**Comment by jamesmccannon02** [comment]
Hi, currently this plug uses a different connection method so it wouldn't work within the software that I am distributing ans as it stands it would likely be very complicated for me to program it currently as i don't have the hardware avalable to test pre-release code. Although, googling came up with someone else who is working on this. this is the link [https://github.com/Tyfy/OctoPrint-TapoSmartplug](https://github.com/Tyfy/OctoPrint-TapoSmartplug). I believe it may be a little buggy but worth a try.

**Comment by NpFaith** [comment]
Thanks for the help I will check the link. Keep the good work. Best regards.

A quinta, 15/07/2021, 10:32, jamesmccannon02 ***@***.***>
escreveu:
