### ISSUE TITLE
HS100 doesn't turn off the plug

### ISSUE THREAD

**Issue by TWIISTED-STUDIOS** [jamesmccannon02/OctoPrint-Tplinkautoshutdown#67]
Trying to use this with the Kasa HS100 the IP is correct the settings don't find the device or the version or anything like that, then when you use the buttons to shut down the plug to test it disconnects octo print from the printer but the printer stays active.

Hardware version 4.1
Firmware version 1.1.0

**Comment by jamesmccannon02** [comment]
HI is this still an issue?

**Comment by dazzlingleadalpaca** [comment]
I'm having the same issue with both the Kasa strip (KP303, Hardware 1.0, Firmware 1.0.11) and the single plug (HS103, Hardware 2.1, Firmware 1.1.4)

**Comment by zipgun-f-16** [comment]
Same issue - Octoprint throws an error message: 
`2022-01-24 11:06:54,900 - kasa.protocol - WARNING - Detected protocol reuse between different event loop`

The plug is unresponsive.

HS100
H/W 1.0
Firmware: 1.2.6

**Comment by kaiailan** [comment]
Having same issue with the strip (KP303(au), Hardware 1.0, Firmware 1.0.4 build 210428)
When you use the nav button to shut down the strip, it disconnects octo print from the printer but the printer stays active.

**Comment by dazzlingleadalpaca** [comment]
> Having same issue with the strip (KP303(au), Hardware 1.0, Firmware 1.0.4 build 210428) When you use the nav button to shut down the strip, it disconnects octo print from the printer but the printer stays active.

Mine was fixed with the new update of octoprint.

**Comment by dazzlingleadalpaca** [comment]
> Having same issue with the strip (KP303(au), Hardware 1.0, Firmware 1.0.4 build 210428) When you use the nav button to shut down the strip, it disconnects octo print from the printer but the printer stays active.

Mine was fixed with the new update of octoprint.

**Comment by jamesmccannon02** [comment]
Great thanks for the reply. Greatly appreciated as this plugin is maintained blind due to not actually owning the hardware.

**Comment by kaiailan** [comment]
Thanks for all your help guys. I checked my settings again when I saw the comments. It was my fault, I didn't tick any plugs in setting. Now all works. Great job!~

**Comment by jamesmccannon02** [comment]
Great to hear your problem is solved

**Comment by TWIISTED-STUDIOS** [comment]
I have tried to re test this and it seems that the HS100 plugs just do not work with this, the printer disconnects from the octoprint instance but the plug that controls the printer just stays active. 

On the configuration when you enter the IP address and then go to configure it you are just met with undefined, I'm assuming this is because of the firmware update that happened to the hs100 that causes the way the API talks to IoT devices to break
