### ISSUE TITLE
Choosing an outlet on the HS107 SmartPlug

### ISSUE THREAD

**Issue by klmullen** [jamesmccannon02/OctoPrint-Tplinkautoshutdown#69]
The KASA HS107 has two independent outlets. How do you designate which outlet you want to address?

**Comment by jamesmccannon02** [comment]
Within settings you can click on the plug-in and then you can select which plug to use. Select smart strip if it’s capable of multiple ports. Not tested it though on the specific plug so please let me know how it goes

**Comment by klmullen** [comment]
Treating it as a SmartStrip did the trick. Thanks -- Kile
