### ISSUE TITLE
Cant install via URL

### ISSUE THREAD

**Issue by realbadfox** [jamesmccannon02/OctoPrint-Tplinkautoshutdown#8]
I try to install via URL in PluginManager, but i didn't work:

ERROR: Could not find a version that satisfies the requirement python-kasa (from OctoPrint-Tplinkautoshutdown==0.1.3) (from versions: none)
ERROR: No matching distribution found for python-kasa (from OctoPrint-Tplinkautoshutdown==0.1.3)
Fehler!
Could not parse output from pip, see plugin_pluginmanager_console.log for generated output

**Comment by jamesmccannon02** [comment]
Can you confirm if you are running python 3 or python 2. For me. Alternatively if you upload you log file i will figure it out myself.

**Comment by realbadfox** [comment]
here you are
[octoprint.log](https://github.com/jamesmccannon02/OctoPrint-Tplinkautoshutdown/files/6002520/octoprint.log)

**Comment by jamesmccannon02** [comment]
Ok, that log seems to be missing what i am looking for. If you re-start octoprint and then look in the log, you should see something such as 

![image](https://user-images.githubusercontent.com/10836951/108355638-03312780-71e3-11eb-829c-323a64b2478b.png)

This will list your python version. If it is python2, your software OS is out of date. There are two options, OctoPrint developed a conversion tool to python3 or you will need to re-install OctoPrint. Currently OctoPrint is in a conversion state as python2 gets discontinued this year and will loose all support. 

If this is the issue, once it is confirmed, i can send some information over to help the transition.

**Comment by realbadfox** [comment]
hardware:
|      cores: 4
|      freq: 1500.0
|      ram: 3959975936
|  os:
|      bits: 32
|      id: linux
|      platform: linux2
|  plugins:
|      pi_support:
|          model: Raspberry Pi 4 Model B Rev 1.1
|          octopi_version: 0.17.0
|          throttle_state: '0x0'
|  python:
|      pip: 20.3.4
|      version: 2.7.16
|      virtualenv: /home/pi/oprint

**Comment by jamesmccannon02** [comment]
Ok, so your issue is that you are running python 2. So you need to either re-install octopi as the new version is now python 3 or follow the tutorial to convert your current version to python 3

[https://octoprint.org/blog/2020/09/10/upgrade-to-py3/](https://octoprint.org/blog/2020/09/10/upgrade-to-py3/)

**Comment by jamesmccannon02** [comment]
[https://octoprint.org/download/](https://octoprint.org/download/)

**Comment by realbadfox** [comment]
Perfect, i upgraded python now the installation worked

**Comment by jamesmccannon02** [comment]
Hope you enjoy it. Currently very basic but i am working on new features as we speak. Any ideas are welcomed

**Comment by realbadfox** [comment]
I have much ideas.
Where should I write them?

**Comment by jamesmccannon02** [comment]
[https://github.com/jamesmccannon02/OctoPrint-Tplinkautoshutdown/discussions/13](https://github.com/jamesmccannon02/OctoPrint-Tplinkautoshutdown/discussions/13)

Here would be great just opened this discussion.

**Comment by realbadfox** [comment]
1) Make not such a big button, only a Icon would be great
2) only one Button, which turns off AND on
3) support for more than one Plug, I use 2! One for Printer, one for LED Light
